FROM rust AS builder

RUN update-ca-certificates

WORKDIR /roboscape_build

COPY . .
WORKDIR /roboscape_build/roboscapesim-api
RUN cargo b -r

FROM debian:bookworm-slim

RUN apt-get update
RUN apt-get install -y libssl-dev

WORKDIR /roboscape
COPY --from=builder /roboscape_build/target/release/roboscape* .
EXPOSE 5001
CMD [ "./roboscapesim-api" ]
