FROM rust:slim-trixie AS builder

RUN update-ca-certificates

WORKDIR /roboscape_build

COPY . .
WORKDIR /roboscape_build/roboscapesim-api
RUN cargo b -r

FROM debian:trixie-slim

RUN apt-get update
RUN apt-get install -y libssl-dev ca-certificates
RUN update-ca-certificates

WORKDIR /roboscape
COPY --from=builder /roboscape_build/target/release/roboscapesim-api .
EXPOSE 5001
CMD [ "./roboscapesim-api" ]
