FROM --platform=${BUILDPLATFORM:-linux/amd64} rust AS builder

ARG TARGETPLATFORM
ARG BUILDPLATFORM

RUN update-ca-certificates

WORKDIR /roboscape_build

COPY . .
WORKDIR /roboscape_build/roboscapesim-server
RUN cargo b -r

FROM debian:bookworm-slim

RUN apt-get update
RUN apt-get install -y libssl-dev ca-certificates
RUN update-ca-certificates

WORKDIR /roboscape
COPY --from=builder /roboscape_build/target/release/roboscapesim-server .
EXPOSE 3000
CMD [ "./roboscapesim-server" ]
