FROM caddy:2-alpine

RUN apk add --no-cache curl nss-tools openssl jq

COPY update_caddyfile.sh .
COPY Caddyfile.template .

RUN chmod +x update_caddyfile.sh

CMD [ "sh", "-c", "./update_caddyfile.sh && caddy run --config Caddyfile" ]