pub const DYNAMIC_ENTITY_LIMIT: usize = 25;
pub const KINEMATIC_ENTITY_LIMIT: usize = 100;
// TODO: Give visual only entities a separate limit
pub const VISUAL_ONLY_ENTITY_LIMIT: usize = 250;
pub const ROBOT_LIMIT: usize = 4;

pub const MAX_COORD: f32 = 10000.0;

pub const AVAILABLETEXTURES: [&str; 15] = [
    "brick",
    "bricks",
    "cobble",
    "crate",
    "dirt",
    "grass",
    "gravel",
    "grid",
    "lava",
    "sand",
    "sandstone",
    "stone",
    "stone_brick",
    "tree",
    "wood",
];

pub const AVAILABLEMESHES: [&str; 64] = [
    "cactus_short",
    "cactus_tall",
    "chest",
    "chest_opt",
    "grass",
    "fence_simple",
    "house_type01",
    "house_type02",
    "house_type03",
    "house_type04",
    "house_type05",
    "house_type06",
    "log",
    "log_large",
    "log_stack",
    "log_stackLarge",
    "mushroom_red",
    "mushroom_redGroup",
    "mushroom_redTall",
    "mushroom_tan",
    "mushroom_tanGroup",
    "mushroom_tanTall",
    "parallax_robot",
    "sign",
    "small_buildingA",
    "small_buildingB",
    "small_buildingC",
    "small_buildingD",
    "small_buildingE",
    "small_buildingF",
    "sphere",
    "stump_round",
    "stump_square",
    "tree_blocks",
    "tree_cone",
    "tree_default",
    "tree_detailed",
    "tree_fat",
    "tree_oak",
    "tree_palmDetailedShort",
    "tree_palmDetailedTall",
    "tree_pineDefaultA",
    "tree_pineDefaultB",
    "tree_pineGroundA",
    "tree_pineGroundB",
    "tree_pineRoundA",
    "tree_pineRoundB",
    "tree_pineRoundC",
    "tree_pineRoundD",
    "tree_pineRoundE",
    "tree_pineRoundF",
    "tree_pineSmallA",
    "tree_pineSmallB",
    "tree_pineSmallC",
    "tree_pineSmallD",
    "tree_pineTallA",
    "tree_pineTallB",
    "tree_pineTallC",
    "tree_pineTallD",
    "tree_plateau",
    "tree_simple",
    "tree_small",
    "tree_tall",
    "tree_thin",
];