[package]
name = "roboscapesim-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.86"
js-sys = "0.3.63"
web-sys = { version = "0.3.63", features = ["console"] }
getrandom = { version = "0.2", features = ["js"] }
roboscapesim-common = { path = "../roboscapesim-common" }
neo-babylon = "0.1.1"
cyberdeck-client-web-sys = { version = "0.1.0" }
netsblox-extension-macro = "0.1"
netsblox-extension-util = "^0.1.2"
console_error_panic_hook = "0.1.7"

[build-dependencies]
netsblox-extension-util = "*"
