name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push API
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        platforms: linux/amd64
        file: Dockerfile-api
        push: true
        tags: gstein17/roboscapesim-rs-api:latest

  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Server
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        platforms: linux/amd64
        file: Dockerfile-server
        push: true
        tags: gstein17/roboscapesim-rs-server:latest
    - name: Build and push Server ARM
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        platforms: linux/arm64
        file: Dockerfile-server
        push: true
        tags: gstein17/roboscapesim-rs-server:latest

