name: Docker Image CI Server

on:
  push:
    branches: [ "master" ]
    paths:
      - 'roboscapesim-server/**'

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Server AMD64
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        platforms: linux/amd64
        file: Dockerfile-server
        push: true
        tags: gstein17/roboscapesim-rs-server:latest
   - name: Build and push Server ARM
     uses: docker/build-push-action@v5.1.0
     with:
       context: .
       platforms: linux/arm64
       file: Dockerfile-server
       push: true
       tags: gstein17/roboscapesim-rs-server:latest

